### ISSUE TITLE
study.ts 구현

### ISSUE THREAD

**Issue by smj53** [chshin59/discord-study-bot#10]
일단 동작만 되게 만들기는 했는데 창호님 코드 보다가 제 코드를 보니 너무 더럽네요ㅋㅋㅋ..
조금 더 고쳐서 올릴까요? 아니면 일단 PR 올리고 리뷰를 통해 조금씩 고쳐나갈까요?
[코드](https://github.com/smj53/discord-study-bot/commit/9b4fc99d92530dae35761048ead0ceec7255bf84)

**Comment by chshin59** [comment]
일단 PR올리고 고치는게 어떨까요? 근데 #8 뒤에 붙은 커밋이라 rebase가 필요해 보이네요. 제걸 빨리 처리했어야하는데ㅠㅠ

**Comment by smj53** [comment]
> 오 동작하면 일단 PR올리고 고치는게 어떨까요? 근데 #8 뒤에 붙은 커밋이라 rebase가 필요해 보이네요. 제걸 빨리 처리했어야하는데ㅠㅠ

아 cherry-pick을 한 번 써보려고는 했어요 ㅋㅋㅋ 브랜치 그냥 새로 파서 제 커밋만 cherry-pick..
rebase로 #8 커밋 지우고 올리면 되는거죠?
