### ISSUE TITLE
휴식 기능

### ISSUE THREAD

**Issue by smj53** [chshin59/discord-study-bot#15]
## Why?
- 오랫동안 모각코 진행 시, 중간에 쉬는 시간 처리를 해서 순공부시간을 확인하기 위해
- 쉬는 시간을 직접 재야 하는 불편함을 해소하기 위해

## How?
- `StudySession`에 `restTime` 변수 추가
- **휴식 시작 command** 실행 시 `restTime`에 현재 시간 할당
    - `restTime`이 이미 존재한다면 실행 불가(`이미 휴식 중입니다.`)
- **휴식 종료 command** 실행 시 `현재 시간값` - `restTime의 시간값`을 계산하여 **notion 휴식 시간 속성 update**
    - `restTime`이 존재하지 않는다면 실행 불가(`휴식 중이 아닙니다.`)
- **스터디 종료** 시 `restTime` 변수에 값이 존재한다면, 휴식 종료 command 사용 시와 동일하게 **notion 휴식시간 속성 update**
- **스터디 시작** 시 이전 세션을 이어서 해서 `restTime` 변수에 값이 존재하는 경우에는?
    - 휴식 중에 잠깐 튕겼다가 들어오는 경우를 고려하여 휴식을 이어서 한다.(restTime을 지우지 않고, 휴식 중 상태) _> 저는 이게 맞다고 생각합니다._
    - 스터디 시작이라는 명시적인 행동을 했으므로 `restTime` 자체를 제거한다.

## 고민거리
- `restTime` 변수 외에 `totalRestTime`을 둬서 notion 페이지를 조회하지 않고 휴식 시간 속성을 update할 수 있게 할 것인지
- 스터디 시간 5분 이하를 확인할 때, 휴식시간까지 고려할 것인지
    - 원래 짧은 시간 텀을 준 이유가 실수로 들어왔다가 나갔을 때 노션이 생성되는 것을 방지하기 위해서였기 때문에 굳이 고려할 필요가 없다고 생각합니다. 일부러 들어오자마자 휴식하실 분들도 아니고...
    - 그렇지만 들어오자마자 일이 생겨서 휴식하고 잠시 갔다왔다가 5분 후에 바로 나가시는 경우가 없진 않겠군요. 제가 그런 경우에는 노션 지우고 싶긴 하겠네요.

## 결론
- `restTime` 변수에 값이 존재하면 휴식을 이어서
- `totalRestTime` 변수 사용
    - 스터디 시작 시, 새로운 세션을 생성한다면 변수 초기화 필요
- 스터디 시간 확인 시 휴식시간까지 고려

다른 의견은 언제나 환영입니다!

**Comment by chshin59** [comment]
기존 기능과 결합하면서 복잡해진 부분이 있네요ㅠㅠ

> * **휴식 시작 command** 실행 시 `restTime`에 현재 시간 할당
>   
>   * `restTime`이 이미 존재한다면 실행 불가(`이미 휴식 중입니다.`)
> * **휴식 종료 command** 실행 시 `현재 시간값` - `restTime의 시간값`을 계산하여 **notion 휴식 시간 속성 update**
>   
>   * `restTime`이 존재하지 않는다면 실행 불가(`휴식 중이 아닙니다.`)

일단 위의 최소 기능을 먼저 구현하고 특수한 상황을 추가하는 게 어떨까요? 휴식 중에 잠깐 튕겼다가 들어오는 경우까지는 지금 생각하기엔 조금  많은 경우를 따지는 것 같습니다. 일단 [mvp](https://blog.crisp.se/wp-content/uploads/2016/01/Making-sense-of-MVP-.jpg)부터 만들어보죠~:smile:
