### ISSUE TITLE
'라운지' 음성채널 접속 시 노션 생성하지 않기

### ISSUE THREAD

**Issue by smj53** [chshin59/discord-study-bot#5]
저희가 보통 라운지에서 주간 모임을 하고 라운지는 자유롭게(ㅎㅎㅎ) 사용하곤 하니까
이외의 음성채널(공부방, 집중 공부방)에 들어갔을 때만 노션 생성을 했으면 좋겠습니다.

만약 다른 음성채널을 더 생성하실 계획이 있다면 화이트리스트로 넣을지 블랙리스트로 뺄지를 고민해봐야 될 것 같습니다.
좀 더 나가면 서버장이 커맨드 활용해서 채널 블랙리스트(혹은 화이트리스트) 추가가 가능하면 좋을 것 같습니다. 이러면 또 세팅 저장이 필요하겠네요

ps. todo list에 수정하려고 해봤는데 수정이 안 되네요 😂
처음 말씀드리는 기능이라 따로 issue를 쓸 생각이긴 했습니다만
라벨도 안 달려서 임시로 discussion 말머리를 달았습니다 😁

@chshin59

**Comment by chshin59** [comment]
> 저희가 보통 라운지에서 주간 모임을 하고 라운지는 자유롭게(ㅎㅎㅎ) 사용하곤 하니까 이외의 음성채널(공부방, 집중 공부방)에 들어갔을 때만 노션 생성을 했으면 좋겠습니다.

좋은 의견 감사합니다:smile:

**Comment by chshin59** [comment]
voiceStateUpdate라는 이벤트가 발생하는 조건이 3가지이고(채널 입장, 이동, 퇴장)  
음성 채널의 종류도 있어서 조건 분기를 조금 고민해보고 적용해보겠습니다~

**Comment by chshin59** [comment]
> ps. todo list에 수정하려고 해봤는데 수정이 안 되네요 joy 처음 말씀드리는 기능이라 따로 issue를 쓸 생각이긴 했습니다만 라벨도 안 달려서 임시로 discussion 말머리를 달았습니다 grin

알고보니 Collaborator 라는게 있네요 초대 드렸으니 수락하시면 저장소 쓰기 관리 권한 생길겁니다 :smile:

@smj53
