### ISSUE TITLE
알림 toggle 커맨드

### ISSUE THREAD

**Issue by smj53** [chshin59/discord-study-bot#9]
### Why?
- 디버깅 및 개발할 때마다 배포 중인 서버를 끄기는 어렵기 때문

### How?
- `src/discord/index.ts`에 boolean 값 추가
    ```javascript
    export default class Discord {
    ///// ....
        public static alarmFlag: boolean = true;
    ///// ....
    ```
- command를 이용해서 boolean값 변경
    ```javascript
    // src/discord/commands/toggle-alarm.ts

    async function execute(interaction: ChatInputCommandInteraction) {
      Discord.alarmFlag = !Discord.alarmFlag;
      await interaction.reply({
        content: `알림 기능 ${Discord.alarmFlag ? "on" : "off"}`,
        ephemeral: true,
      });
    }
    ```
[전체코드](https://github.com/smj53/discord-study-bot/commit/ff4720f4f6cfd6d05d543a4ac5f6042d2762b14b)

### 의논 사항
1. 여러 사람이 동시에 각자의 local에서 toggle을 해버리면 문제가 생길 수도.
    - 문제: 어떤 사람 로컬에서는 off인데 어떤 사람 로컬에서는 on인 상황이 발생 가능. toggle을 아무리해도 절대 안 꺼지게 됨
    - 차라리 on/off를 따로 만들기? > 쓸데없이 코드가 많아진다.
    - 로컬에서는 그냥 주석처리하자 (ㅋㅋㅋ)
2. 네이밍
    - 파일명: toggle-alarm.ts
    - 커맨드명: toggle (대문자를 못 쓰네요...)
    - 변수명: alarmFlag
3. 기본값: true? > 배포 시 안 켜도 되도록. 단, 디버깅할 때는 코드를 바꾸거나 매번 toggle을 해줘야 하는 불편함 존재
    - 배포를 많이 하는 게 아니니까 기본값을 false로?
    - local일 때는 false, 배포일 때는 true > 가능한지?
4. Discord class 자체에 boolean을 갖고 있는 게 괜찮을지
5. getter, setter를 사용하지 않고 바로 접근하는 것 괜찮을지

디버깅/개발 시 배포 서버를 끄지 않고도 알림을 끌 수 있는 다른 방법도 환영합니다!!!!
- 개발 중임을 알 수 있는 트리거가 있으면 좋겠다. 봇이 두 개 이상이 켜져 있음을 감지할 수는 없나? 근데 감지할 수 있다고 해도 다른 봇들에 broadcasting이 가능한지가 또 문제...
- 될지는 모르겠는 꼼수: Role을 하나(`개발자`) 만들어서 개발 시 자신을 `개발자`로 변경. `개발자`인 사람이 있으면 alarm 끄고 없으면 켜기 (RoleUpdate 이벤트가 존재. 처음 실행할 때도 role 받아올 수 있을 것 같다.)
    ```
    interaction에 들어있는 GuildMember 속성 일부

    member: GuildMember {
        joinedTimestamp: 1674734964768,
        premiumSinceTimestamp: null,
        nickname: '정세미',
        pending: false,
        communicationDisabledUntilTimestamp: null,
        _roles: [], // role 존재
    ...
    ```
    - role 변경 방법
        1. discord에서 직접 바꿀지 > 창호님 말고 바꿀 수 있을지?
        2. 로컬에만 존재하는 코드를 실행해서 처리할지
    - 다른 비슷한 꼼수: sticker 생성/삭제, 스레드 생성/삭제, scheduledEvent 생성/삭제

**Comment by chshin59** [comment]
https://nodejs.dev/en/learn/nodejs-the-difference-between-development-and-production/
nodejs 에서는 개발과 배포를 분리할 때 요 방법을 많이 쓰긴 합니다.

cloudtype의 설정-환경변수에 자동으로 NODE_ENV가 production으로 들어가 있습니다.
![image](https://user-images.githubusercontent.com/97646064/223975236-293d1e26-8f4e-444f-b5dd-f8d95bc239df.png)

따라서 로컬에선 NODE_ENV가 undefined 혹은 development(설정을 해 준 경우)일테니 아래코드를 추가하고 조건문으로 나누면 되지 않을까 싶습니다.
```typescipt
// dotenv.ts
export const NODE_ENV = process.env.NODE_ENV ?? "development";

//
if (NODE_ENV === 'development') {
  알람x
}

if (NODE_ENV === 'production') {
  알람o
}
```

**Comment by smj53** [comment]
> 따라서 로컬에선 NODE_ENV가 undefined 혹은 development(설정을 해 준 경우)일테니 아래코드를 추가하고 조건문으로 나누면 되지 않을까 싶습니다.

그렇다면 알림 toggle 기능을 사용한다고 하면, 알림을 보낼지 말지에 대한 기본값 설정을 NODE_ENV에 따라 해주게 되겠네요?

> 완성된 코드는 저렇게 분리할 수 있는데 새로운 기능 만들 때는 결국 알림이 가나(기능이 작동하나) 확인해야 하니 알림을 보내보는 수밖에 없겠네요;;

동작 확인을 위해 알림 기능을 켤 필요가 있다는 말씀이신가요?

흠.. 지금 문제가
1. 로컬에서 디버깅할 때, 서버에도 이벤트가 전달되어 불필요한 알림이 전송된다.
2. 알림이 켜 있는 것 자체도 문제다. 디버깅을 위해 왔다갔다 하면서 불필요한 알림이 전송된다.
3. 그렇다고 개발 중에 아예 알림을 끄면 알림 설정이 필요한 디버깅이 불가능하다.
인 것 같네요.

제 생각에는 로컬에서는 필요에 따라 주석처리로 막는 게 편할 것 같고, 서버는 개발 중에는 알림을 안 보내게 하는 게 나을 것 같습니다. 토글 기능을 사용한다면 로컬 봇 돌리기 전에 끄고 돌리는 방법이 있겠네요. 여전히 여러 사람이 한 번에 디버깅할 때는 문제가 되겠지만요.
알림 보내는 쪽에서 처리하는 게 아니라 아예 이벤트 받는 곳에서 막아도 괜찮을 것 같네요.(만약 이벤트로 처리한다면 해당 이벤트 제외) 노션 기능 올리고 나서 디버깅할 때 노션 생성/삭제 막 될 걸 생각하면...

**Comment by smj53** [comment]
일단 굳이 구현이 필요 없다는 쪽으로 결론이 난 것 같아서 이슈 닫겠습니다.
